aggr: mean
concat_states: false
dropout: 0
edge_dim: 16
edge_mode: 1
epochs: 100
gnn_activation: relu
impute_activation: relu
impute_hiddens: ''
known: 0.7
log_dir: y0
lr: 0.001
model_types: EGSAGE_EGSAGE
node_dim: 16
node_mode: 0
norm_embs: null
opt: adam
opt_decay_rate: 0.9
opt_decay_step: 1000
opt_restart: 0
opt_scheduler: none
post_hiddens: null
predict_hiddens: ''
seed: 10
split_by: y
split_sample: 0
train_edge: 0.7
train_y: 0.7
valid: 0
weight_decay: 0
